// FONT SIZE
export const HEADER_ONE_FONT_SIZE = 26;
export const HEADER_TWO_FONT_SIZE = 20;
export const BUTTON_FONT_SIZE = 20;
export const SENTENCE_FONT_SIZE = 16;

// FONT FAMILY
export const HEADER_ONE_FONT_FAMILY = 'MontserratBold';
export const HEADER_TWO_FONT_FAMILY = 'MontserratSemiBold';
export const BUTTON_FONT_FAMILY = 'MontserratBold';
export const SENTENCE_FONT_FAMILY = 'OpenSansRegular';

// FONT HORIZONTAL PADDING 
export const HEADER_ONE_HORIZONTAL_PADDING = 5;
export const HEADER_TWO_HORIZONTAL_PADDING = 5;
export const BUTTON_HORIZONTAL_PADDING = 5;
export const SENTENCE_HORIZONTAL_PADDING = 5;
// FONT VERTICAL PADDING 
export const HEADER_ONE_VERTICAL_PADDING = 10;
export const HEADER_TWO_VERTICAL_PADDING = 8;
export const BUTTON_VERTICAL_PADDING = 6;
export const SENTENCE_VERTICAL_PADDING = 4;
// FONT HORIZONTAL MARGIN 
export const HEADER_ONE_HORIZONTAL_MARGIN = 5;
export const HEADER_TWO_HORIZONTAL_MARGIN = 5;
export const BUTTON_HORIZONTAL_MARGIN = 20;
export const SENTENCE_HORIZONTAL_MARGIN = 5;
// FONT VERTICAL MARGIN 
export const HEADER_ONE_VERTICAL_MARGIN = 10;
export const HEADER_TWO_VERTICAL_MARGIN = 9;
export const BUTTON_VERTICAL_MARGIN = 6;
export const SENTENCE_VERTICAL_MARGIN = 4;